name: copyable
description: A Flutter package for giving and standardizing copy functionality to Dart classes.
version: 0.0.1+1
author: Juan Diego Fajardo <jfajardo@mit.edu>
homepage: https://github.com/kuanfajardo/copier.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6
  # Generator
  analyzer: ^0.36.3
  build: ^1.1.4
  source_gen: ^0.9.4
  code_builder: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

